<template>
  <div class="app-container">
    <el-alert title="先登记抖音链接；没有真实逐字稿时会停在“等待逐字稿”，不得确认或用于生成。确认后再在问题详情中说明采用理由、学习点与不可复制边界。" type="warning" :closable="false" class="mb16" />
    <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" label-width="76px"><el-form-item label="租户" prop="tenantId"><el-input v-model="queryParams.tenantId" clearable style="width:170px" /></el-form-item><el-form-item label="标题" prop="titleSnapshot"><el-input v-model="queryParams.titleSnapshot" clearable @keyup.enter="handleQuery" /></el-form-item><el-form-item label="受众" prop="audienceType"><el-select v-model="queryParams.audienceType" clearable style="width:160px"><el-option label="B2B 美业老板" value="B2B_BEAUTY_OWNER" /><el-option label="B2C 门店消费者" value="B2C_STORE_CONSUMER" /></el-select></el-form-item><el-form-item label="状态" prop="reviewStatus"><el-select v-model="queryParams.reviewStatus" clearable style="width:150px"><el-option v-for="x in statusOptions" :key="x.value" :label="x.label" :value="x.value" /></el-select></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item></el-form>
    <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="['topic:source:add']">登记链接</el-button></el-col><el-col :span="1.5"><el-button type="success" plain icon="Edit" :disabled="single" @click="handleUpdate()" v-hasPermi="['topic:source:edit']">补录/修改</el-button></el-col><el-col :span="1.5"><el-button type="warning" plain icon="CircleCheck" :disabled="single" @click="handleConfirm()" v-hasPermi="['topic:source:confirm']">人工确认</el-button></el-col><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" /></el-row>
    <el-table v-loading="loading" :data="sourceList" @selection-change="handleSelectionChange"><el-table-column type="selection" width="55" /><el-table-column label="标题 / 原链接" min-width="250"><template #default="s"><a :href="s.row.sourceUrl" target="_blank" rel="noopener">{{ s.row.titleSnapshot || s.row.sourceUrl }}</a></template></el-table-column><el-table-column label="前三秒钩子" prop="hookTextSnapshot" min-width="240" show-overflow-tooltip /><el-table-column label="受众" prop="audienceType" width="170" /><el-table-column label="状态" width="130"><template #default="s"><el-tag :type="tagType(s.row.reviewStatus)">{{ statusLabel(s.row.reviewStatus) }}</el-tag></template></el-table-column><el-table-column label="逐字稿" width="105"><template #default="s"><el-tag :type="s.row.transcriptSnapshot ? 'success' : 'info'">{{ s.row.transcriptSnapshot ? '已补录' : '待补录' }}</el-tag></template></el-table-column><el-table-column label="操作" fixed="right" width="110"><template #default="s"><el-button link type="primary" icon="Edit" @click="handleUpdate(s.row)" v-hasPermi="['topic:source:edit']" /><el-button link type="warning" icon="CircleCheck" :disabled="s.row.reviewStatus === 'CONFIRMED'" @click="handleConfirm(s.row)" v-hasPermi="['topic:source:confirm']" /></template></el-table-column></el-table>
    <pagination v-show="total>0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    <el-dialog :title="title" v-model="open" width="720px" append-to-body><el-form ref="sourceRef" :model="form" :rules="rules" label-width="108px"><el-form-item label="租户" prop="tenantId"><el-input v-model="form.tenantId" :disabled="!!form.id" /></el-form-item><el-form-item label="抖音链接" prop="sourceUrl"><el-input v-model="form.sourceUrl" :disabled="!!form.id" /></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="平台" prop="sourcePlatform"><el-input v-model="form.sourcePlatform" placeholder="douyin" /></el-form-item></el-col><el-col :span="12"><el-form-item label="受众" prop="audienceType"><el-select v-model="form.audienceType" style="width:100%"><el-option label="B2B 美业老板" value="B2B_BEAUTY_OWNER" /><el-option label="B2C 门店消费者" value="B2C_STORE_CONSUMER" /></el-select></el-form-item></el-col></el-row><el-form-item label="真实标题"><el-input v-model="form.titleSnapshot" /></el-form-item><el-form-item label="真实逐字稿"><el-input v-model="form.transcriptSnapshot" type="textarea" :rows="4" /></el-form-item><el-form-item label="前三秒钩子"><el-input v-model="form.hookTextSnapshot" type="textarea" :rows="2" /></el-form-item><el-form-item label="数据快照"><el-input v-model="form.performanceSnapshot" type="textarea" :rows="2" /></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" :rows="2" /></el-form-item></el-form><template #footer><el-button type="primary" @click="submitForm">确 定</el-button><el-button @click="cancel">取 消</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { getCurrentInstance, reactive, ref, toRefs } from 'vue'; import type { ComponentInternalInstance } from 'vue'; import { addTopicSourceCase, confirmTopicSourceCase, getTopicSourceCase, listTopicSourceCase, updateTopicSourceCase } from '@/api/topic/sourceCase'; import type { TopicSourceCase, TopicSourceCaseQueryParams } from '@/types'
const { proxy }=getCurrentInstance() as ComponentInternalInstance; const sourceList=ref<TopicSourceCase[]>([]),loading=ref(true),showSearch=ref(true),total=ref(0),open=ref(false),title=ref(''),ids=ref<string[]>([]),single=ref(true); const statusOptions=[{value:'PENDING_TRANSCRIPT',label:'等待逐字稿'},{value:'PENDING_REVIEW',label:'待人工确认'},{value:'CONFIRMED',label:'已确认'}]; const data=reactive({form:{} as TopicSourceCase,queryParams:{pageNum:1,pageSize:10,tenantId:'local-preview'} as TopicSourceCaseQueryParams,rules:{tenantId:[{required:true,message:'租户不能为空',trigger:'blur'}],sourceUrl:[{required:true,message:'抖音链接不能为空',trigger:'blur'}],sourcePlatform:[{required:true,message:'平台不能为空',trigger:'blur'}],audienceType:[{required:true,message:'受众不能为空',trigger:'change'}]}}); const {form,queryParams,rules}=toRefs(data)
function getList(){loading.value=true;listTopicSourceCase(queryParams.value).then(r=>{sourceList.value=r.rows;total.value=r.total;loading.value=false}).catch(()=>loading.value=false)} function reset(){form.value={tenantId:queryParams.value.tenantId||'local-preview',sourcePlatform:'douyin',audienceType:'B2B_BEAUTY_OWNER'};proxy?.resetForm('sourceRef')} function cancel(){open.value=false;reset()} function handleQuery(){queryParams.value.pageNum=1;getList()} function resetQuery(){proxy?.resetForm('queryRef');queryParams.value.tenantId='local-preview';handleQuery()} function handleSelectionChange(v:TopicSourceCase[]){ids.value=v.map(x=>x.id as string);single.value=v.length!==1} function handleAdd(){reset();open.value=true;title.value='登记爆款视频链接'} function handleUpdate(row?:TopicSourceCase){reset();getTopicSourceCase(row?.id||ids.value[0]).then(r=>{form.value=r.data||{};open.value=true;title.value='补录逐字稿与拆解'})} function submitForm(){proxy?.$refs.sourceRef.validate((ok:boolean)=>{if(!ok)return;(form.value.id?updateTopicSourceCase(form.value):addTopicSourceCase(form.value)).then(()=>{proxy?.$modal.msgSuccess('保存成功');open.value=false;getList()})})} function handleConfirm(row?:TopicSourceCase){const id=row?.id||ids.value[0];proxy?.$modal.confirm('确认后逐字稿和钩子将冻结；确认真实来源？').then(()=>confirmTopicSourceCase(id)).then(()=>{proxy?.$modal.msgSuccess('已确认');getList()}).catch(()=>{})} function statusLabel(v?:string){return statusOptions.find(x=>x.value===v)?.label||v||'-'} function tagType(v?:string){return v==='CONFIRMED'?'success':v==='PENDING_REVIEW'?'warning':'info'} getList()
</script>
